name: laundry_management_system
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  another_flushbar: ^1.12.30
  badges: ^3.1.1
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.8.0
  cupertino_icons: ^1.0.2
  cupertino_stepper: ^0.2.1
  equatable: ^2.0.5
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  firebase_core_web: ^2.2.1
  firebase_database: ^10.2.3
  firebase_storage: ^11.2.3
  
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.0.0
  flutter_iconly: ^1.0.2
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.2
  font_awesome_flutter: ^10.3.0
  google_fonts: ^4.0.3
  google_nav_bar: ^5.0.6
  image_cropper: ^1.4.0
  image_picker: ^0.8.9
  intl: ^0.18.1
  introduction_screen: ^3.1.4
  like_button: ^2.0.5
  lottie: ^2.4.0
  material_design_icons_flutter: ^6.0.7096
  permission_handler: ^10.3.0
  provider: ^6.0.5
  responsive_framework: ^0.2.0
  sizer: ^2.0.15
  smooth_page_indicator: ^1.0.1
  water_drop_nav_bar: ^2.2.0+5
  http: ^0.13.4
  url_launcher: ^6.1.12
  awesome_dialog: ^3.1.0
  merchant_evc_plus: ^0.0.2
  firebase_messaging: ^14.6.5
  
  flutter_local_notifications: ^15.1.0+1
  modal_progress_hud_nsn: ^0.4.0
  flare_flutter: ^3.0.2
  firebase_analytics: ^10.4.4
  intl_phone_number_input: ^0.7.3+1
  shared_preferences: ^2.2.0
  get_storage: ^2.1.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1


flutter_icons:
  android : true
  ios : true
  image_path : "assets/logo.png"
  adaptive_icon_background : "#0eb5f2"

flutter_native_splash :
 android : true
 ios : true
 web : false
#  background_image : "#0eb5f2"
 color : "#0eb5f2"
 image : "assets/logo.png"

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/sliderpics/
    - assets/font/
  #   - images/a_dot_ham.jpeg
